<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Vehicle's parameters (remember to enter the model parameters below) -->
    <xacro:property name="remaro_auv_length" value="3.00"/>
    <xacro:property name="remaro_auv_radius" value="-0.1"/>

    <!-- Buoyancy info -->
    <xacro:property name="remaro_auv_buoyancy_kg" value="2"/> 
    <xacro:property name="remaro_auv_rho"  value="1027.5"/>  
    <xacro:property name="remaro_auv_cob" value="0 0 0.2"/>

    <!-- Volume approximated as cylinder with hemispherical ends -->
    <xacro:property
      name="remaro_auv_volume"
      value="${1/3*pi*remaro_auv_radius*remaro_auv_radius*(3*remaro_auv_length-2*remaro_auv_radius)}"
    />

    <!-- Mass info -->
    <xacro:property
      name="remaro_auv_mass"
      value="${remaro_auv_volume*remaro_auv_rho-remaro_auv_buoyancy_kg}"
    />
    <xacro:property name="remaro_auv_cog"  value="0 0 0"/>

    <xacro:macro name="remaro_auv_hydro_model" params="namespace">
      <!-- List of hydrodynamic models this robot's links -->
      <link name="${namespace}/base_link">
        <!-- This flag will make the link neutrally buoyant -->
        <neutrally_buoyant>0</neutrally_buoyant>

        <!-- Link's volume -->
        <volume>${remaro_auv_volume}</volume>

        <!-- Link's bounding box, it is used to recalculate the immersed
        volume when close to the surface.
        This is a workaround the invalid bounding box given by Gazebo-->
        <box>
          <width> ${remaro_auv_volume/(2*remaro_auv_length*remaro_auv_radius)} </width>
          <length>${remaro_auv_length}</length>
          <height>${2*remaro_auv_radius}</height>
        </box>

        <!-- Center of buoyancy -->
        <center_of_buoyancy>${remaro_auv_cob}</center_of_buoyancy>

        <!-- Fossen's equation of motion; values interpolated from example AUVs-->
        <hydrodynamic_model>
          <type>fossen</type>
          <added_mass>
             50     0     0     0     0     0
              0   400     0     0     0     0
              0     0   400     0     0     0
              0     0     0     0     0     0
              0     0     0     0   400     0
              0     0     0     0     0   400          
          </added_mass>
          <linear_damping>-30 -600 -400 -30 -100 -100</linear_damping>
          <linear_damping_forward_speed>-30 -600 -400 -30 -100 -100</linear_damping_forward_speed>
          <quadratic_damping>0 0 0 0 0 0</quadratic_damping>
        </hydrodynamic_model>

      </link>
    </xacro:macro>

</robot>
